/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CarModelDto
 */
export interface CarModelDto {
    /**
     * 
     * @type {string}
     * @memberof CarModelDto
     */
    'brand'?: string;
    /**
     * 
     * @type {string}
     * @memberof CarModelDto
     */
    'model'?: string;
    /**
     * 
     * @type {string}
     * @memberof CarModelDto
     */
    'fuelType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CarModelDto
     */
    'gearBox'?: string;
    /**
     * 
     * @type {number}
     * @memberof CarModelDto
     */
    'fuelTankCapacity'?: number;
    /**
     * 
     * @type {number}
     * @memberof CarModelDto
     */
    'year'?: number;
    /**
     * 
     * @type {number}
     * @memberof CarModelDto
     */
    'seatCapacity'?: number;
}

