/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CarImageDto } from './car-image-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CarLocationDto } from './car-location-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CarModelDto } from './car-model-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ReviewDto } from './review-dto';

/**
 * 
 * @export
 * @interface CarDetailDto
 */
export interface CarDetailDto {
    /**
     * 
     * @type {string}
     * @memberof CarDetailDto
     */
    'description'?: string;
    /**
     * 
     * @type {Array<ReviewDto>}
     * @memberof CarDetailDto
     */
    'reviews'?: Array<ReviewDto>;
    /**
     * 
     * @type {CarLocationDto}
     * @memberof CarDetailDto
     */
    'location'?: CarLocationDto;
    /**
     * 
     * @type {string}
     * @memberof CarDetailDto
     */
    'id'?: string;
    /**
     * 
     * @type {CarModelDto}
     * @memberof CarDetailDto
     */
    'carModel'?: CarModelDto;
    /**
     * 
     * @type {string}
     * @memberof CarDetailDto
     */
    'licensePlate'?: string;
    /**
     * 
     * @type {number}
     * @memberof CarDetailDto
     */
    'pricePerDay'?: number;
    /**
     * 
     * @type {string}
     * @memberof CarDetailDto
     */
    'currency'?: string;
    /**
     * 
     * @type {Array<CarImageDto>}
     * @memberof CarDetailDto
     */
    'images'?: Array<CarImageDto>;
    /**
     * 
     * @type {boolean}
     * @memberof CarDetailDto
     */
    'isAvailable'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CarDetailDto
     */
    'averageRating'?: number;
    /**
     * 
     * @type {number}
     * @memberof CarDetailDto
     */
    'reviewsCount'?: number;
}

