/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CarImageDto } from './car-image-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CarModelDto } from './car-model-dto';

/**
 * 
 * @export
 * @interface CarDto
 */
export interface CarDto {
    /**
     * 
     * @type {string}
     * @memberof CarDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CarDto
     */
    'title': string;
    /**
     * 
     * @type {CarModelDto}
     * @memberof CarDto
     */
    'carModel': CarModelDto;
    /**
     * 
     * @type {string}
     * @memberof CarDto
     */
    'licensePlate': string;
    /**
     * 
     * @type {number}
     * @memberof CarDto
     */
    'pricePerDay': number;
    /**
     * 
     * @type {string}
     * @memberof CarDto
     */
    'currency': string;
    /**
     * 
     * @type {Array<CarImageDto>}
     * @memberof CarDto
     */
    'images': Array<CarImageDto>;
    /**
     * 
     * @type {boolean}
     * @memberof CarDto
     */
    'isAvailable': boolean;
    /**
     * 
     * @type {number}
     * @memberof CarDto
     */
    'averageRating': number;
    /**
     * 
     * @type {number}
     * @memberof CarDto
     */
    'reviewsCount': number;
}

