/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CarModelDto } from './car-model-dto';

/**
 * 
 * @export
 * @interface CarLocationDto
 */
export interface CarLocationDto {
    /**
     * 
     * @type {string}
     * @memberof CarLocationDto
     */
    'carId': string;
    /**
     * 
     * @type {string}
     * @memberof CarLocationDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CarLocationDto
     */
    'imageUrl': string;
    /**
     * 
     * @type {number}
     * @memberof CarLocationDto
     */
    'pricePerDay': number;
    /**
     * 
     * @type {string}
     * @memberof CarLocationDto
     */
    'currency': string;
    /**
     * 
     * @type {CarModelDto}
     * @memberof CarLocationDto
     */
    'carModel': CarModelDto;
    /**
     * 
     * @type {number}
     * @memberof CarLocationDto
     */
    'longitude': number;
    /**
     * 
     * @type {number}
     * @memberof CarLocationDto
     */
    'latitude': number;
}

