/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CarLocationDto } from './car-location-dto';

/**
 * 
 * @export
 * @interface CreateRentalRequest
 */
export interface CreateRentalRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRentalRequest
     */
    'carId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateRentalRequest
     */
    'pickupDate': string;
    /**
     * 
     * @type {string}
     * @memberof CreateRentalRequest
     */
    'dropoffDate': string;
    /**
     * 
     * @type {CarLocationDto}
     * @memberof CreateRentalRequest
     */
    'pickupLocation': CarLocationDto;
    /**
     * 
     * @type {CarLocationDto}
     * @memberof CreateRentalRequest
     */
    'dropoffLocation': CarLocationDto;
}

