/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CarLocationDto } from './car-location-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { UploadCarImageRequest } from './upload-car-image-request';

/**
 * 
 * @export
 * @interface CreateCarCommand
 */
export interface CreateCarCommand {
    /**
     * 
     * @type {number}
     * @memberof CreateCarCommand
     */
    'year'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCarCommand
     */
    'modelId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCarCommand
     */
    'licensePlate'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCarCommand
     */
    'pricePerDay'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCarCommand
     */
    'currency'?: string;
    /**
     * 
     * @type {CarLocationDto}
     * @memberof CreateCarCommand
     */
    'location'?: CarLocationDto;
    /**
     * 
     * @type {Array<UploadCarImageRequest>}
     * @memberof CreateCarCommand
     */
    'images'?: Array<UploadCarImageRequest>;
}

