/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentRequest
 */
export interface PaymentRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentRequest
     */
    'rentalId': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequest
     */
    'method': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequest
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequest
     */
    'returnUrl'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PaymentRequest
     */
    'metadata'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof PaymentRequest
     */
    'paymentProviderId': string;
}

