/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentResponse
 */
export interface PaymentResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentResponse
     */
    'transactionId'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentResponse
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof PaymentResponse
     */
    'paymentUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentResponse
     */
    'message'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PaymentResponse
     */
    'providerData'?: { [key: string]: string; };
}

