/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterUserCommand
 */
export interface RegisterUserCommand {
    /**
     * 
     * @type {string}
     * @memberof RegisterUserCommand
     */
    'name': string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserCommand
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserCommand
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserCommand
     */
    'password': string;
}

