/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CarDto } from './car-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CarLocationDto } from './car-location-dto';

/**
 * 
 * @export
 * @interface RentalDto
 */
export interface RentalDto {
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'id'?: string;
    /**
     * 
     * @type {CarDto}
     * @memberof RentalDto
     */
    'carInfo'?: CarDto;
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'pickupDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'dropoffDate'?: string;
    /**
     * 
     * @type {CarLocationDto}
     * @memberof RentalDto
     */
    'pickupLocation'?: CarLocationDto;
    /**
     * 
     * @type {CarLocationDto}
     * @memberof RentalDto
     */
    'dropoffLocation'?: CarLocationDto;
    /**
     * 
     * @type {number}
     * @memberof RentalDto
     */
    'totalCost'?: number;
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'currency'?: string;
    /**
     * 
     * @type {number}
     * @memberof RentalDto
     */
    'status'?: number;
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'createdAt'?: string;
}

