/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LocationDto } from './location-dto';

/**
 * 
 * @export
 * @interface RentalDto
 */
export interface RentalDto {
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'carId': string;
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'pickupDate': string;
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'dropoffDate': string;
    /**
     * 
     * @type {LocationDto}
     * @memberof RentalDto
     */
    'pickupLocation': LocationDto;
    /**
     * 
     * @type {LocationDto}
     * @memberof RentalDto
     */
    'dropoffLocation': LocationDto;
    /**
     * 
     * @type {number}
     * @memberof RentalDto
     */
    'totalCost': number;
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'currency': string;
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof RentalDto
     */
    'createdAt': string;
}

