/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReviewDto
 */
export interface ReviewDto {
    /**
     * 
     * @type {string}
     * @memberof ReviewDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewDto
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewDto
     */
    'userName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewDto
     */
    'carId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewDto
     */
    'carDetails'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReviewDto
     */
    'rating'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReviewDto
     */
    'comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewDto
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewDto
     */
    'imageUrl'?: string;
}

