/* tslint:disable */
/* eslint-disable */
/**
 * Morent.WebApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CarDto } from './car-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { RentalDto } from './rental-dto';

/**
 * 
 * @export
 * @interface UserCarsReviewDto
 */
export interface UserCarsReviewDto {
    /**
     * 
     * @type {RentalDto}
     * @memberof UserCarsReviewDto
     */
    'rental': RentalDto;
    /**
     * 
     * @type {CarDto}
     * @memberof UserCarsReviewDto
     */
    'car': CarDto;
    /**
     * 
     * @type {string}
     * @memberof UserCarsReviewDto
     */
    'carImageUrl': string;
    /**
     * 
     * @type {number}
     * @memberof UserCarsReviewDto
     */
    'rating': number;
    /**
     * 
     * @type {string}
     * @memberof UserCarsReviewDto
     */
    'comment': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserCarsReviewDto
     */
    'isReviewed': boolean;
}

